###########################################################
#                                                         #
# Copyright (c)                                           #
#                                                         #
# The Verifiable & Control-Theoretic Robotics (VECTR) Lab #
# University of California, Los Angeles                   #
#                                                         #
# Authors: Kenny J. Chen, Ryan Nemiroff, Brett T. Lopez   #
# Contact: {kennyjchen, ryguyn, btlopez}@ucla.edu         #
#                                                         #
###########################################################

dlio:

  frames:
    odom: odom
    baselink: dlio/base_link  # name of the base link frame to publish
    lidar: dlio/os_sensor  # name of the lidar frame to publish
    imu: dlio/os_imu  # name of the imu frame to publish
    publishDeskewedInLidarFrame: true # whether to publish the deskewed point cloud in the lidar frame (true) or odom frame (false)

  map:
    waitUntilMove: false
    dense:
      filtered: false
    sparse:
      leafSize: 0.25

  odom:

    gravity: 9.80665
    computeTimeOffset: true

    imu:
      approximateGravity: true
      calibration:
        gyro: true
        accel: true
        time: 3.5
      bufferSize: 5000

    preprocessing:
      cropBoxFilter:
        size: 0.35
      voxelFilter:
        res: 0.25

    keyframe:
      threshD: 1.0
      threshR: 45.0

    submap:
      keyframe:
        knn: 10
        kcv: 10
        kcc: 10
    gicp:
      minNumPoints: 64
      kCorrespondences: 16
      maxCorrespondenceDistance: 0.5
      maxIterations: 32
      transformationEpsilon: 0.01
      rotationEpsilon: 0.01
      initLambdaFactor: 1e-9

    geo:
      Kp: 4.5
      Kv: 11.25
      Kq: 4.0
      Kab: 2.25
      Kgb: 1.0
      abias_max: 5.0
      gbias_max: 2.5
